steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - fullfilment
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=nodejs20
  - --allow-unauthenticated